name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.10.0
  flutter_svg: ^2.2.1
  url_launcher: ^6.3.2
  firebase_core: ^4.2.0

  # Date and time formatting
  intl: ^0.19.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
