// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWxwKvTpiiRxW2GgKtK6VlqFRa436R80',
    appId: '1:885536488765:web:86a7f6759fba5e54a15954',
    messagingSenderId: '885536488765',
    projectId: 'butchee-6c727',
    authDomain: 'butchee-6c727.firebaseapp.com',
    storageBucket: 'butchee-6c727.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKQuNeEfFbd3RyT5NmBk45YTghKPD1__E',
    appId: '1:885536488765:android:83076736e6920624a15954',
    messagingSenderId: '885536488765',
    projectId: 'butchee-6c727',
    storageBucket: 'butchee-6c727.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIAy9sZoPaJ14ghsWn4Sl3p3cz8rqB8_A',
    appId: '1:885536488765:ios:fcd1bbdd13ea77a5a15954',
    messagingSenderId: '885536488765',
    projectId: 'butchee-6c727',
    storageBucket: 'butchee-6c727.firebasestorage.app',
    iosBundleId: 'com.butchee.app',
  );
}
